[phases.setup]
nixPkgs = ['nodejs_18', 'bun']

[phases.install]
cmds = [
  'npm install -g corepack@0.24.1 && corepack enable',
  'bun i --no-save'
]

[phases.build]
cmds = ['turbo run build --filter=web']

[phases.start]
cmds = ['turbo run start --filter=web']
